/******************************************************************************/
/****         Generated by IBExpert 2007.05.03 19/12/2021 20:21:45         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\3LM\Projeto\DataBase\DB_Funcionario.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;

